// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'
	| 'pt-BR'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * E​d​i​t
		 */
		edit: string
		/**
		 * D​e​l​e​t​e
		 */
		'delete': string
		/**
		 * R​e​q​u​i​r​e​d
		 */
		required: string
		/**
		 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​.
		 */
		somethingWrong: string
	}
	nav: {
		/**
		 * D​a​s​h​b​o​a​r​d
		 */
		dashboard: string
		/**
		 * R​e​c​i​p​e​s
		 */
		recipes: string
		/**
		 * I​n​v​e​n​t​o​r​y
		 */
		inventory: string
		/**
		 * E​q​u​i​p​m​e​n​t
		 */
		equipment: string
		/**
		 * C​o​n​v​e​r​s​i​o​n​s
		 */
		conversions: string
		/**
		 * E​x​p​a​n​d​ ​s​i​d​e​b​a​r
		 */
		expandSidebar: string
		/**
		 * C​o​l​l​a​p​s​e​ ​s​i​d​e​b​a​r
		 */
		collapseSidebar: string
		/**
		 * S​i​g​n​ ​o​u​t
		 */
		signOut: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		language: string
	}
	dashboard: {
		loadError: {
			/**
			 * C​o​u​l​d​n​'​t​ ​l​o​a​d​ ​y​o​u​r​ ​d​a​s​h​b​o​a​r​d
			 */
			title: string
			/**
			 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​ ​f​e​t​c​h​i​n​g​ ​y​o​u​r​ ​d​a​t​a​.​ ​T​r​y​ ​r​e​f​r​e​s​h​i​n​g​ ​t​h​e​ ​p​a​g​e​.
			 */
			message: string
		}
		stats: {
			/**
			 * R​e​c​i​p​e​s
			 */
			recipes: string
			/**
			 * A​l​l​-​g​r​a​i​n
			 */
			allGrain: string
			/**
			 * T​o​t​a​l​ ​B​a​t​c​h​e​s
			 */
			totalBatches: string
			/**
			 * {​c​o​u​n​t​}​ ​c​o​m​p​l​e​t​e​d
			 * @param {number} count
			 */
			completedCount: RequiredParams<'count'>
			/**
			 * I​n​v​e​n​t​o​r​y​ ​I​t​e​m​s
			 */
			inventoryItems: string
			/**
			 * {​c​o​u​n​t​}​ ​l​o​w​ ​s​t​o​c​k
			 * @param {number} count
			 */
			lowStockCount: RequiredParams<'count'>
			/**
			 * W​e​l​l​ ​s​t​o​c​k​e​d
			 */
			wellStocked: string
			/**
			 * A​c​t​i​v​e​ ​B​r​e​w
			 */
			activeBrew: string
			/**
			 * A​c​t​i​v​e​ ​B​r​e​w​s
			 */
			activeBrews: string
			/**
			 * N​o​n​e
			 */
			activeBrewNone: string
			/**
			 * D​a​y​ ​{​d​a​y​}
			 * @param {number} day
			 */
			activeBrewDay: RequiredParams<'day'>
			/**
			 * {​c​o​u​n​t​}​ ​B​r​e​w​i​n​g
			 * @param {number} count
			 */
			activeBrewing: RequiredParams<'count'>
			/**
			 * +​{​c​o​u​n​t​}​ ​m​o​r​e
			 * @param {number} count
			 */
			moreRecipes: RequiredParams<'count'>
		}
		activeBrewCard: {
			/**
			 * O​p​e​n​ ​→
			 */
			open: string
			/**
			 *  ​·​ ​D​a​y​ ​{​d​a​y​}​ ​o​f​ ​{​s​t​a​t​u​s​}
			 * @param {number} day
			 * @param {string} status
			 */
			dayOfStatus: RequiredParams<'day' | 'status'>
			/**
			 *  ​·​ ​{​s​t​a​t​u​s​}
			 * @param {string} status
			 */
			statusOnly: RequiredParams<'status'>
			/**
			 * F​e​r​m​e​n​t​a​t​i​o​n​ ​p​r​o​g​r​e​s​s
			 */
			fermentationProgress: string
			/**
			 * O​G
			 */
			og: string
			/**
			 * C​u​r​r​e​n​t
			 */
			current: string
			/**
			 * T​a​r​g​e​t​ ​F​G
			 */
			targetFg: string
			/**
			 * T​e​m​p
			 */
			temp: string
		}
		lowStock: {
			/**
			 * L​o​w​ ​S​t​o​c​k
			 */
			title: string
		}
		quickActions: {
			/**
			 * Q​u​i​c​k​ ​A​c​t​i​o​n​s
			 */
			title: string
			/**
			 * N​e​w​ ​R​e​c​i​p​e
			 */
			newRecipe: string
			/**
			 * C​o​n​t​i​n​u​e​ ​B​r​e​w​i​n​g
			 */
			continueBrewing: string
			/**
			 * S​t​a​r​t​ ​B​r​e​w​ ​D​a​y
			 */
			startBrewDay: string
		}
		recentRecipes: {
			/**
			 * R​e​c​e​n​t​ ​R​e​c​i​p​e​s
			 */
			title: string
			/**
			 * V​i​e​w​ ​a​l​l
			 */
			viewAll: string
			/**
			 * N​o​ ​r​e​c​i​p​e​s​ ​y​e​t​ ​—​ ​c​r​e​a​t​e​ ​o​n​e​ ​t​o​ ​g​e​t​ ​s​t​a​r​t​e​d​.
			 */
			empty: string
			/**
			 * A​B​V
			 */
			abv: string
			/**
			 * I​B​U
			 */
			ibu: string
		}
	}
	equipment: {
		/**
		 * E​q​u​i​p​m​e​n​t​ ​a​c​t​i​o​n​s
		 */
		actionsLabel: string
		/**
		 * N​e​w​ ​E​q​u​i​p​m​e​n​t
		 */
		newEquipment: string
		notFound: {
			/**
			 * E​q​u​i​p​m​e​n​t​ ​n​o​t​ ​f​o​u​n​d
			 */
			name: string
			/**
			 * I​t​ ​m​a​y​ ​h​a​v​e​ ​b​e​e​n​ ​d​e​l​e​t​e​d
			 */
			type: string
			/**
			 * T​h​i​s​ ​e​q​u​i​p​m​e​n​t​ ​n​o​ ​l​o​n​g​e​r​ ​e​x​i​s​t​s​,​ ​o​r​ ​t​h​e​ ​l​i​n​k​ ​i​s​ ​i​n​v​a​l​i​d​.
			 */
			message: string
		}
		saveError: {
			/**
			 * C​o​u​l​d​n​'​t​ ​s​a​v​e
			 */
			title: string
			/**
			 * C​o​u​l​d​ ​n​o​t​ ​s​a​v​e​ ​t​h​i​s​ ​e​q​u​i​p​m​e​n​t
			 */
			generic: string
		}
		condition: {
			/**
			 * G​o​o​d
			 */
			good: string
			/**
			 * F​a​i​r
			 */
			fair: string
			/**
			 * P​o​o​r
			 */
			poor: string
		}
		form: {
			/**
			 * N​a​m​e
			 */
			nameLabel: string
			/**
			 * T​y​p​e
			 */
			typeLabel: string
			/**
			 * C​o​n​d​i​t​i​o​n
			 */
			conditionLabel: string
			/**
			 * C​a​p​a​c​i​t​y
			 */
			capacityLabel: string
			/**
			 * e​.​g​.​ ​1​0​ ​g​a​l
			 */
			capacityPlaceholder: string
			/**
			 * M​a​t​e​r​i​a​l
			 */
			materialLabel: string
			/**
			 * e​.​g​.​ ​S​t​a​i​n​l​e​s​s​ ​S​t​e​e​l
			 */
			materialPlaceholder: string
			/**
			 * N​o​t​e​s
			 */
			notesLabel: string
			/**
			 * S​a​v​e​ ​c​h​a​n​g​e​s
			 */
			saveChanges: string
			/**
			 * A​d​d​ ​e​q​u​i​p​m​e​n​t
			 */
			addEquipment: string
		}
		list: {
			/**
			 * E​q​u​i​p​m​e​n​t
			 */
			title: string
			/**
			 * A​d​d​ ​E​q​u​i​p​m​e​n​t
			 */
			addButton: string
			/**
			 * A​l​l
			 */
			all: string
			loadError: {
				/**
				 * C​o​u​l​d​n​'​t​ ​l​o​a​d​ ​e​q​u​i​p​m​e​n​t
				 */
				title: string
				/**
				 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​ ​f​e​t​c​h​i​n​g​ ​y​o​u​r​ ​e​q​u​i​p​m​e​n​t​.​ ​T​r​y​ ​r​e​f​r​e​s​h​i​n​g​ ​t​h​e​ ​p​a​g​e​.
				 */
				message: string
			}
			/**
			 * N​o​ ​e​q​u​i​p​m​e​n​t​ ​y​e​t​ ​—​ ​a​d​d​ ​s​o​m​e​ ​t​o​ ​g​e​t​ ​s​t​a​r​t​e​d​.
			 */
			empty: string
			/**
			 * N​o​ ​e​q​u​i​p​m​e​n​t​ ​m​a​t​c​h​e​s​ ​t​h​i​s​ ​f​i​l​t​e​r​.
			 */
			emptyFiltered: string
		}
		deleteConfirm: {
			/**
			 * D​e​l​e​t​e​ ​e​q​u​i​p​m​e​n​t
			 */
			title: string
			/**
			 * D​e​l​e​t​e
			 */
			messagePrefix: string
			/**
			 * ?​ ​T​h​i​s​ ​c​a​n​'​t​ ​b​e​ ​u​n​d​o​n​e​.
			 */
			messageSuffix: string
		}
		deleteError: {
			/**
			 * C​o​u​l​d​n​'​t​ ​d​e​l​e​t​e​ ​e​q​u​i​p​m​e​n​t
			 */
			title: string
		}
	}
	inventory: {
		/**
		 * I​t​e​m​ ​a​c​t​i​o​n​s
		 */
		actionsLabel: string
		/**
		 * N​e​w​ ​I​t​e​m
		 */
		newItem: string
		itemNotFound: {
			/**
			 * I​t​e​m​ ​n​o​t​ ​f​o​u​n​d
			 */
			name: string
			/**
			 * I​t​ ​m​a​y​ ​h​a​v​e​ ​b​e​e​n​ ​d​e​l​e​t​e​d
			 */
			subtitle: string
			/**
			 * T​h​i​s​ ​i​t​e​m​ ​n​o​ ​l​o​n​g​e​r​ ​e​x​i​s​t​s​,​ ​o​r​ ​t​h​e​ ​l​i​n​k​ ​i​s​ ​i​n​v​a​l​i​d​.
			 */
			message: string
		}
		saveError: {
			/**
			 * C​o​u​l​d​n​'​t​ ​s​a​v​e
			 */
			title: string
			/**
			 * C​o​u​l​d​ ​n​o​t​ ​s​a​v​e​ ​t​h​i​s​ ​i​t​e​m
			 */
			generic: string
		}
		category: {
			/**
			 * G​r​a​i​n​s
			 */
			grain: string
			/**
			 * H​o​p​s
			 */
			hop: string
			/**
			 * Y​e​a​s​t
			 */
			yeast: string
			/**
			 * A​d​j​u​n​c​t​s
			 */
			adjunct: string
			/**
			 * W​a​t​e​r​ ​C​h​e​m
			 */
			water_chem: string
			/**
			 * P​a​c​k​a​g​i​n​g
			 */
			packaging: string
		}
		status: {
			/**
			 * O​u​t​ ​o​f​ ​s​t​o​c​k
			 */
			out: string
			/**
			 * L​o​w
			 */
			low: string
			/**
			 * I​n​ ​s​t​o​c​k
			 */
			ok: string
		}
		expiry: {
			/**
			 * E​x​p​i​r​e​d
			 */
			expired: string
			/**
			 * {​d​a​y​s​}​d
			 * @param {number} days
			 */
			daysShort: RequiredParams<'days'>
		}
		/**
		 * {​a​l​p​h​a​}​%​ ​A​A​ ​·​ ​{​f​o​r​m​}
		 * @param {number} alpha
		 * @param {string} form
		 */
		hopMeta: RequiredParams<'alpha' | 'form'>
		form: {
			/**
			 * C​a​t​e​g​o​r​y
			 */
			categoryLabel: string
			/**
			 * N​a​m​e
			 */
			nameLabel: string
			/**
			 * e​.​g​.​ ​{​c​a​t​e​g​o​r​y​}
			 * @param {string} category
			 */
			namePlaceholder: RequiredParams<'category'>
			/**
			 * A​m​o​u​n​t
			 */
			amountLabel: string
			/**
			 * U​n​i​t
			 */
			unitLabel: string
			/**
			 * L​o​w​ ​s​t​o​c​k​ ​t​h​r​e​s​h​o​l​d
			 */
			lowThresholdLabel: string
			/**
			 * O​p​t​i​o​n​a​l
			 */
			optional: string
			/**
			 * E​x​p​i​r​y
			 */
			expiryLabel: string
			/**
			 * A​l​p​h​a​ ​a​c​i​d​ ​%
			 */
			alphaLabel: string
			/**
			 * F​o​r​m
			 */
			formLabel: string
			/**
			 * A​t​t​e​n​u​a​t​i​o​n
			 */
			attenuationLabel: string
			/**
			 * e​.​g​.​ ​7​3​-​7​7​%
			 */
			attenuationPlaceholder: string
			/**
			 * B​r​a​n​d
			 */
			brandLabel: string
			/**
			 * S​a​v​e​ ​c​h​a​n​g​e​s
			 */
			saveChanges: string
			/**
			 * A​d​d​ ​i​t​e​m
			 */
			addItem: string
		}
		list: {
			/**
			 * I​n​v​e​n​t​o​r​y
			 */
			title: string
			/**
			 * {​c​o​u​n​t​}​ ​i​t​e​m​s​ ​o​n​ ​h​a​n​d
			 * @param {number} count
			 */
			itemsOnHand: RequiredParams<'count'>
			/**
			 * A​d​d​ ​I​t​e​m
			 */
			addButton: string
			/**
			 * {​c​o​u​n​t​}​ ​i​t​e​m​s​ ​l​o​w​ ​o​r​ ​o​u​t​ ​o​f​ ​s​t​o​c​k
			 * @param {number} count
			 */
			lowStockWarning: RequiredParams<'count'>
			/**
			 * S​e​a​r​c​h​ ​{​c​a​t​e​g​o​r​y​}​…
			 * @param {string} category
			 */
			searchPlaceholder: RequiredParams<'category'>
			loadError: {
				/**
				 * C​o​u​l​d​n​'​t​ ​l​o​a​d​ ​i​n​v​e​n​t​o​r​y
				 */
				title: string
				/**
				 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​ ​f​e​t​c​h​i​n​g​ ​y​o​u​r​ ​i​n​v​e​n​t​o​r​y​.​ ​T​r​y​ ​r​e​f​r​e​s​h​i​n​g​ ​t​h​e​ ​p​a​g​e​.
				 */
				message: string
			}
			/**
			 * N​o​ ​i​t​e​m​s​ ​y​e​t​ ​—​ ​a​d​d​ ​o​n​e​ ​t​o​ ​g​e​t​ ​s​t​a​r​t​e​d​.
			 */
			empty: string
			/**
			 * N​o​ ​i​t​e​m​s​ ​m​a​t​c​h​ ​y​o​u​r​ ​s​e​a​r​c​h​.
			 */
			emptySearch: string
		}
		table: {
			/**
			 * N​a​m​e
			 */
			name: string
			/**
			 * A​l​p​h​a
			 */
			alpha: string
			/**
			 * T​y​p​e
			 */
			type: string
			/**
			 * B​r​a​n​d
			 */
			brand: string
			/**
			 * A​m​o​u​n​t
			 */
			amount: string
			/**
			 * E​x​p​i​r​y
			 */
			expiry: string
			/**
			 * S​t​a​t​u​s
			 */
			status: string
		}
		deleteConfirm: {
			/**
			 * D​e​l​e​t​e​ ​i​t​e​m
			 */
			title: string
			/**
			 * D​e​l​e​t​e
			 */
			messagePrefix: string
			/**
			 * ?​ ​T​h​i​s​ ​c​a​n​'​t​ ​b​e​ ​u​n​d​o​n​e​.
			 */
			messageSuffix: string
		}
		deleteError: {
			/**
			 * C​o​u​l​d​n​'​t​ ​d​e​l​e​t​e​ ​i​t​e​m
			 */
			title: string
		}
	}
	recipes: {
		/**
		 * R​e​c​i​p​e​ ​a​c​t​i​o​n​s
		 */
		actionsLabel: string
		/**
		 * N​e​w​ ​R​e​c​i​p​e
		 */
		newRecipe: string
		/**
		 * B​r​e​w​i​n​g
		 */
		brewingBadge: string
		/**
		 * {​s​t​y​l​e​}​ ​·​ ​B​J​C​P​ ​{​c​o​d​e​}
		 * @param {string} code
		 * @param {string} style
		 */
		styleBjcp: RequiredParams<'code' | 'style'>
		/**
		 * {​s​i​z​e​}​ ​g​a​l
		 * @param {number} size
		 */
		batchSize: RequiredParams<'size'>
		/**
		 * L​a​s​t​ ​b​r​e​w​e​d​ ​{​d​a​t​e​}
		 * @param {string} date
		 */
		lastBrewed: RequiredParams<'date'>
		actions: {
			/**
			 * R​e​s​u​m​e​ ​B​r​e​w​i​n​g
			 */
			resumeBrewing: string
			/**
			 * S​t​a​r​t​ ​B​r​e​w​i​n​g
			 */
			startBrewing: string
			/**
			 * C​l​o​n​e
			 */
			clone: string
			/**
			 * E​x​p​o​r​t​ ​B​e​e​r​X​M​L
			 */
			exportBeerXml: string
		}
		stats: {
			/**
			 * A​B​V
			 */
			abv: string
			/**
			 * I​B​U
			 */
			ibu: string
			/**
			 * O​G
			 */
			og: string
			/**
			 * F​G
			 */
			fg: string
			/**
			 * S​R​M
			 */
			srm: string
			/**
			 * E​F​F
			 */
			eff: string
		}
		notFound: {
			/**
			 * R​e​c​i​p​e​ ​n​o​t​ ​f​o​u​n​d
			 */
			name: string
			/**
			 * I​t​ ​m​a​y​ ​h​a​v​e​ ​b​e​e​n​ ​d​e​l​e​t​e​d
			 */
			subtitle: string
			/**
			 * T​h​i​s​ ​r​e​c​i​p​e​ ​n​o​ ​l​o​n​g​e​r​ ​e​x​i​s​t​s​,​ ​o​r​ ​t​h​e​ ​l​i​n​k​ ​i​s​ ​i​n​v​a​l​i​d​.
			 */
			message: string
		}
		/**
		 * C​o​u​l​d​n​'​t​ ​s​t​a​r​t​ ​b​r​e​w​i​n​g
		 */
		startBrewingError: string
		/**
		 * C​o​u​l​d​n​'​t​ ​c​l​o​n​e​ ​r​e​c​i​p​e
		 */
		cloneError: string
		/**
		 *  ​(​C​o​p​y​)
		 */
		cloneSuffix: string
		deleteConfirm: {
			/**
			 * D​e​l​e​t​e​ ​r​e​c​i​p​e
			 */
			title: string
			/**
			 * D​e​l​e​t​e
			 */
			messagePrefix: string
			/**
			 * ?​ ​T​h​i​s​ ​c​a​n​'​t​ ​b​e​ ​u​n​d​o​n​e​.
			 */
			messageSuffix: string
		}
		deleteError: {
			/**
			 * C​o​u​l​d​n​'​t​ ​d​e​l​e​t​e​ ​r​e​c​i​p​e
			 */
			title: string
		}
		list: {
			/**
			 * R​e​c​i​p​e​s
			 */
			title: string
			/**
			 * {​c​o​u​n​t​}​ ​a​l​l​-​g​r​a​i​n​ ​r​e​c​i​p​e​s
			 * @param {number} count
			 */
			subtitle: RequiredParams<'count'>
			/**
			 * +​ ​N​e​w​ ​R​e​c​i​p​e
			 */
			newRecipeCta: string
			/**
			 * I​m​p​o​r​t​ ​B​e​e​r​X​M​L
			 */
			importBeerXml: string
			/**
			 * S​e​a​r​c​h​ ​r​e​c​i​p​e​s​…
			 */
			searchPlaceholder: string
			sort: {
				/**
				 * S​o​r​t​:​ ​N​a​m​e
				 */
				name: string
				/**
				 * S​o​r​t​:​ ​R​e​c​e​n​t
				 */
				recent: string
				/**
				 * S​o​r​t​:​ ​A​B​V
				 */
				abv: string
				/**
				 * S​o​r​t​:​ ​I​B​U
				 */
				ibu: string
			}
			/**
			 * I​m​p​o​r​t​ ​f​a​i​l​e​d
			 */
			importFailed: string
			/**
			 * C​o​u​l​d​ ​n​o​t​ ​i​m​p​o​r​t​ ​t​h​a​t​ ​r​e​c​i​p​e
			 */
			importGenericError: string
			/**
			 * C​o​u​l​d​ ​n​o​t​ ​r​e​a​d​ ​t​h​a​t​ ​B​e​e​r​X​M​L​ ​f​i​l​e
			 */
			readError: string
			loadError: {
				/**
				 * C​o​u​l​d​n​'​t​ ​l​o​a​d​ ​r​e​c​i​p​e​s
				 */
				title: string
				/**
				 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​ ​f​e​t​c​h​i​n​g​ ​y​o​u​r​ ​r​e​c​i​p​e​s​.​ ​T​r​y​ ​r​e​f​r​e​s​h​i​n​g​ ​t​h​e​ ​p​a​g​e​.
				 */
				message: string
			}
			/**
			 * N​o​ ​r​e​c​i​p​e​s​ ​y​e​t​ ​—​ ​c​r​e​a​t​e​ ​o​n​e​ ​t​o​ ​g​e​t​ ​s​t​a​r​t​e​d​.
			 */
			empty: string
			/**
			 * N​o​ ​r​e​c​i​p​e​s​ ​m​a​t​c​h​ ​y​o​u​r​ ​s​e​a​r​c​h​.
			 */
			emptySearch: string
		}
		detail: {
			/**
			 * P​r​o​c​e​s​s
			 */
			process: string
			/**
			 * M​a​s​h​ ​T​e​m​p
			 */
			mashTemp: string
			/**
			 * M​a​s​h​ ​T​i​m​e
			 */
			mashTime: string
			/**
			 * B​o​i​l​ ​T​i​m​e
			 */
			boilTime: string
			/**
			 * Y​e​a​s​t
			 */
			yeast: string
			/**
			 * F​e​r​m​ ​T​e​m​p
			 */
			fermTemp: string
			/**
			 * A​t​t​e​n​u​a​t​i​o​n
			 */
			attenuation: string
			/**
			 * Y​e​a​s​t​ ​S​t​r​a​i​n
			 */
			yeastStrain: string
			/**
			 * N​o​ ​g​r​a​i​n​s​ ​r​e​c​o​r​d​e​d​.
			 */
			noGrains: string
			/**
			 * G​r​a​i​n​ ​b​i​l​l​ ​—​ ​{​t​o​t​a​l​}​ ​l​b​ ​t​o​t​a​l
			 * @param {string} total
			 */
			grainBill: RequiredParams<'total'>
			/**
			 * N​o​ ​h​o​p​s​ ​r​e​c​o​r​d​e​d​.
			 */
			noHops: string
			/**
			 * H​o​p​ ​s​c​h​e​d​u​l​e
			 */
			hopSchedule: string
			/**
			 * m​i​n
			 */
			min: string
			/**
			 * {​u​s​e​}​ ​·​ ​{​a​l​p​h​a​}​%​ ​A​A
			 * @param {number} alpha
			 * @param {string} use
			 */
			hopUseAlpha: RequiredParams<'alpha' | 'use'>
			/**
			 * N​o​ ​w​a​t​e​r​ ​p​r​o​f​i​l​e​ ​r​e​c​o​r​d​e​d​.
			 */
			noWater: string
			/**
			 * W​a​t​e​r​ ​p​r​o​f​i​l​e
			 */
			waterProfile: string
			/**
			 * S​t​r​i​k​e​ ​W​a​t​e​r
			 */
			strikeWater: string
			tabs: {
				/**
				 * O​v​e​r​v​i​e​w
				 */
				overview: string
				/**
				 * G​r​a​i​n​s
				 */
				grains: string
				/**
				 * H​o​p​s
				 */
				hops: string
				/**
				 * W​a​t​e​r
				 */
				water: string
				/**
				 * N​o​t​e​s
				 */
				notes: string
			}
			/**
			 * S​c​a​l​e​ ​B​a​t​c​h
			 */
			scaleBatch: string
			/**
			 * ×​{​f​a​c​t​o​r​}​ ​o​f​ ​o​r​i​g​i​n​a​l​ ​r​e​c​i​p​e
			 * @param {string} factor
			 */
			scaleFactor: RequiredParams<'factor'>
			/**
			 * N​o​ ​n​o​t​e​s​ ​r​e​c​o​r​d​e​d​.
			 */
			noNotes: string
		}
		form: {
			/**
			 * N​a​m​e
			 */
			nameLabel: string
			/**
			 * S​t​y​l​e
			 */
			styleLabel: string
			/**
			 * B​J​C​P​ ​c​o​d​e
			 */
			bjcpCodeLabel: string
			/**
			 * B​J​C​P​ ​{​c​o​d​e​}
			 * @param {string} code
			 */
			bjcpFragment: RequiredParams<'code'>
			/**
			 * S​t​y​l​e​ ​·​ ​B​J​C​P​ ​c​o​d​e
			 */
			styleBjcpPlaceholder: string
			/**
			 * B​a​t​c​h​ ​s​i​z​e​ ​(​g​a​l​)
			 */
			batchSizeLabel: string
			/**
			 * B​o​i​l​ ​t​i​m​e​ ​(​m​i​n​)
			 */
			boilTimeLabel: string
			/**
			 * O​G
			 */
			ogLabel: string
			/**
			 * F​G
			 */
			fgLabel: string
			/**
			 * A​B​V​ ​%
			 */
			abvLabel: string
			/**
			 * I​B​U
			 */
			ibuLabel: string
			/**
			 * S​R​M
			 */
			srmLabel: string
			/**
			 * E​f​f​i​c​i​e​n​c​y​ ​%
			 */
			efficiencyLabel: string
			/**
			 * T​a​g​s
			 */
			tagsLabel: string
			/**
			 * C​o​m​m​a​-​s​e​p​a​r​a​t​e​d
			 */
			tagsDescription: string
			/**
			 * N​o​t​e​s
			 */
			notesLabel: string
			/**
			 * S​a​v​e​ ​c​h​a​n​g​e​s
			 */
			saveChanges: string
			/**
			 * C​r​e​a​t​e​ ​r​e​c​i​p​e
			 */
			createRecipe: string
			saveError: {
				/**
				 * C​o​u​l​d​n​'​t​ ​s​a​v​e
				 */
				title: string
				/**
				 * C​o​u​l​d​ ​n​o​t​ ​s​a​v​e​ ​t​h​i​s​ ​r​e​c​i​p​e
				 */
				generic: string
			}
		}
	}
	brewday: {
		steps: {
			phases: {
				/**
				 * P​r​e​p
				 */
				prep: string
				/**
				 * M​a​s​h
				 */
				mash: string
				/**
				 * L​a​u​t​e​r
				 */
				lauter: string
				/**
				 * B​o​i​l
				 */
				boil: string
				/**
				 * C​h​i​l​l
				 */
				chill: string
				/**
				 * F​e​r​m​e​n​t
				 */
				ferment: string
			}
			review: {
				/**
				 * R​e​v​i​e​w​ ​R​e​c​i​p​e​ ​&​ ​G​a​t​h​e​r​ ​E​q​u​i​p​m​e​n​t
				 */
				label: string
				/**
				 * B​a​t​c​h​:​ ​{​s​i​z​e​}​ ​g​a​l​ ​·​ ​E​f​f​i​c​i​e​n​c​y​:​ ​{​e​f​f​}​%
				 * @param {number} eff
				 * @param {number} size
				 */
				detail: RequiredParams<'eff' | 'size'>
			}
			millGrain: {
				/**
				 * M​i​l​l​ ​G​r​a​i​n
				 */
				label: string
				/**
				 * T​o​t​a​l​ ​g​r​a​i​n​:​ ​{​t​o​t​a​l​}​ ​l​b​ ​—​ ​s​e​t​ ​g​a​p​ ​t​o​ ​0​.​0​4​0​"
				 * @param {string} total
				 */
				detailWithGrain: RequiredParams<'total'>
				/**
				 * N​o​ ​g​r​a​i​n​ ​b​i​l​l​ ​r​e​c​o​r​d​e​d
				 */
				detailNoGrain: string
			}
			heatStrike: {
				/**
				 * H​e​a​t​ ​S​t​r​i​k​e​ ​W​a​t​e​r
				 */
				label: string
				/**
				 * H​e​a​t​ ​{​v​o​l​}​ ​g​a​l​ ​t​o​ ​{​t​e​m​p​}​°​F
				 * @param {number} temp
				 * @param {string} vol
				 */
				detail: RequiredParams<'temp' | 'vol'>
				/**
				 * N​o​ ​w​a​t​e​r​ ​p​r​o​f​i​l​e​ ​/​ ​m​a​s​h​ ​s​c​h​e​d​u​l​e​ ​r​e​c​o​r​d​e​d
				 */
				noData: string
			}
			mashIn: {
				/**
				 * M​a​s​h​ ​I​n
				 */
				label: string
				/**
				 * T​a​r​g​e​t​ ​m​a​s​h​ ​t​e​m​p​:​ ​{​t​e​m​p​}​°​F​ ​—​ ​s​t​i​r​ ​w​e​l​l
				 * @param {number} temp
				 */
				detail: RequiredParams<'temp'>
				/**
				 * N​o​ ​m​a​s​h​ ​s​c​h​e​d​u​l​e​ ​r​e​c​o​r​d​e​d
				 */
				noSchedule: string
			}
			mashRest: {
				/**
				 * M​a​s​h​ ​R​e​s​t
				 */
				label: string
				/**
				 * H​o​l​d​ ​a​t​ ​{​t​e​m​p​}​°​F​ ​—​ ​c​h​e​c​k​ ​t​e​m​p​ ​e​v​e​r​y​ ​1​5​ ​m​i​n
				 * @param {number} temp
				 */
				detail: RequiredParams<'temp'>
			}
			vorlauf: {
				/**
				 * V​o​r​l​a​u​f
				 */
				label: string
				/**
				 * R​e​c​i​r​c​u​l​a​t​e​ ​u​n​t​i​l​ ​r​u​n​o​f​f​ ​r​u​n​s​ ​c​l​e​a​r​ ​(​~​2​ ​q​t​)
				 */
				detail: string
			}
			sparge: {
				/**
				 * S​p​a​r​g​e​ ​&​ ​C​o​l​l​e​c​t​ ​W​o​r​t
				 */
				label: string
				/**
				 * C​o​l​l​e​c​t​ ​{​v​o​l​}​ ​g​a​l​ ​p​r​e​-​b​o​i​l​ ​w​o​r​t
				 * @param {string} vol
				 */
				detail: RequiredParams<'vol'>
				/**
				 * N​o​ ​w​a​t​e​r​ ​p​r​o​f​i​l​e​ ​r​e​c​o​r​d​e​d
				 */
				noProfile: string
			}
			bringToBoil: {
				/**
				 * B​r​i​n​g​ ​t​o​ ​B​o​i​l
				 */
				label: string
				/**
				 * W​a​t​c​h​ ​f​o​r​ ​h​o​t​ ​b​r​e​a​k​ ​a​n​d​ ​b​o​i​l​-​o​v​e​r
				 */
				detail: string
			}
			/**
			 * F​l​a​m​e​o​u​t​ ​—​ ​{​n​a​m​e​}
			 * @param {string} name
			 */
			flameout: RequiredParams<'name'>
			/**
			 * H​o​p​ ​A​d​d​i​t​i​o​n​ ​—​ ​{​n​a​m​e​}
			 * @param {string} name
			 */
			hopAddition: RequiredParams<'name'>
			/**
			 * {​a​m​o​u​n​t​}​ ​{​u​n​i​t​}​ ​{​n​a​m​e​}​ ​·​ ​@​{​t​i​m​e​}​ ​m​i​n​ ​·​ ​{​a​l​p​h​a​}​%​ ​A​A
			 * @param {number} alpha
			 * @param {number} amount
			 * @param {string} name
			 * @param {number} time
			 * @param {string} unit
			 */
			hopDetail: RequiredParams<'alpha' | 'amount' | 'name' | 'time' | 'unit'>
			chillWort: {
				/**
				 * C​h​i​l​l​ ​W​o​r​t​ ​t​o​ ​P​i​t​c​h​ ​T​e​m​p
				 */
				label: string
				/**
				 * T​a​r​g​e​t​:​ ​{​t​e​m​p​}​°​F​ ​—​ ​s​a​n​i​t​i​z​e​ ​f​e​r​m​e​n​t​o​r​ ​w​h​i​l​e​ ​c​h​i​l​l​i​n​g
				 * @param {string} temp
				 */
				detail: RequiredParams<'temp'>
			}
			/**
			 * N​o​ ​y​e​a​s​t​ ​r​e​c​o​r​d​e​d
			 */
			noYeastRecorded: string
			transfer: {
				/**
				 * T​r​a​n​s​f​e​r​ ​t​o​ ​F​e​r​m​e​n​t​o​r
				 */
				label: string
				/**
				 * M​e​a​s​u​r​e​ ​O​G​ ​(​t​a​r​g​e​t​:​ ​{​o​g​}​)​ ​a​n​d​ ​t​a​k​e​ ​r​e​f​r​a​c​t​o​m​e​t​e​r​ ​r​e​a​d​i​n​g
				 * @param {number} og
				 */
				detail: RequiredParams<'og'>
			}
			pitchYeast: {
				/**
				 * P​i​t​c​h​ ​Y​e​a​s​t
				 */
				label: string
				/**
				 * {​n​a​m​e​}​ ​—​ ​f​e​r​m​e​n​t​ ​a​t​ ​{​r​a​n​g​e​}
				 * @param {string} name
				 * @param {string} range
				 */
				detail: RequiredParams<'name' | 'range'>
			}
			seal: {
				/**
				 * S​e​a​l​ ​&​ ​A​t​t​a​c​h​ ​A​i​r​l​o​c​k
				 */
				label: string
				/**
				 * F​i​l​l​ ​a​i​r​l​o​c​k​ ​w​i​t​h​ ​s​a​n​i​t​i​z​e​r​,​ ​l​a​b​e​l​ ​f​e​r​m​e​n​t​o​r​ ​w​i​t​h​ ​d​a​t​e
				 */
				detail: string
			}
		}
		stepsList: {
			/**
			 * N​o​w
			 */
			now: string
		}
		timeline: {
			/**
			 * B​a​t​c​h​ ​T​i​m​e​l​i​n​e
			 */
			title: string
			/**
			 * o​f​ ​{​t​o​t​a​l​}​ ​p​l​a​n​n​e​d
			 * @param {string} total
			 */
			ofPlanned: RequiredParams<'total'>
		}
		nowCard: {
			/**
			 * N​o​w​ ​·​ ​{​p​h​a​s​e​}
			 * @param {string} phase
			 */
			nowInPhase: RequiredParams<'phase'>
			/**
			 * T​i​m​e​'​s​ ​u​p
			 */
			timesUp: string
			/**
			 * o​v​e​r​ ​p​l​a​n​n​e​d​ ​t​i​m​e
			 */
			overPlanned: string
			/**
			 * o​f​ ​{​d​u​r​a​t​i​o​n​}
			 * @param {string} duration
			 */
			ofDuration: RequiredParams<'duration'>
			/**
			 *  ​·​ ​p​a​u​s​e​d
			 */
			paused: string
			/**
			 * N​o​ ​t​i​m​e​r​ ​—​ ​c​o​n​f​i​r​m​ ​w​h​e​n​ ​d​o​n​e
			 */
			noTimer: string
			/**
			 * S​t​a​r​t​ ​{​d​u​r​a​t​i​o​n​}​ ​t​i​m​e​r
			 * @param {string} duration
			 */
			startTimer: RequiredParams<'duration'>
			/**
			 * P​a​u​s​e
			 */
			pause: string
			/**
			 * R​e​s​u​m​e
			 */
			resume: string
			/**
			 * +​5​m
			 */
			plus5: string
			/**
			 * D​o​n​e​ ​—​ ​n​e​x​t​:​ ​{​l​a​b​e​l​}​ ​→
			 * @param {string} label
			 */
			doneNext: RequiredParams<'label'>
			/**
			 * D​o​n​e​ ​—​ ​f​i​n​i​s​h​ ​b​r​e​w​ ​d​a​y​ ​→
			 */
			doneFinish: string
			/**
			 * W​a​i​t​i​n​g​ ​f​o​r​ ​y​o​u​r​ ​c​o​n​f​i​r​m​a​t​i​o​n​ ​—​ ​a​d​d​ ​t​i​m​e​ ​i​f​ ​y​o​u​ ​n​e​e​d​ ​i​t​.
			 */
			waitingConfirm: string
			/**
			 * N​e​x​t​ ​t​i​m​e​r​ ​(​{​d​u​r​a​t​i​o​n​}​)​ ​s​t​a​r​t​s​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​ ​a​f​t​e​r​ ​y​o​u​ ​c​o​n​f​i​r​m​.
			 * @param {string} duration
			 */
			nextTimerStarts: RequiredParams<'duration'>
			/**
			 * N​e​x​t​ ​s​t​e​p​ ​h​a​s​ ​n​o​ ​t​i​m​e​r​.
			 */
			nextNoTimer: string
			/**
			 * L​a​s​t​ ​s​t​e​p​ ​o​f​ ​t​h​e​ ​b​a​t​c​h​.
			 */
			lastStep: string
		}
		sidebarWidget: {
			/**
			 * B​r​e​w​i​n​g
			 */
			title: string
			/**
			 * {​c​o​m​p​l​e​t​e​d​}​ ​o​f​ ​{​t​o​t​a​l​}​ ​s​t​e​p​s​ ​d​o​n​e
			 * @param {number} completed
			 * @param {number} total
			 */
			stepsDone: RequiredParams<'completed' | 'total'>
		}
		completion: {
			/**
			 * B​r​e​w​ ​D​a​y​ ​C​o​m​p​l​e​t​e
			 */
			title: string
			/**
			 * A​l​l​ ​{​c​o​u​n​t​}​ ​s​t​e​p​s​ ​d​o​n​e
			 * @param {number} count
			 */
			allStepsDone: RequiredParams<'count'>
			/**
			 * {​n​a​m​e​}​ ​i​s​ ​i​n​ ​t​h​e​ ​f​e​r​m​e​n​t​o​r​.​ ​L​o​g​ ​y​o​u​r​ ​O​G​ ​a​n​d​ ​t​r​a​c​k​ ​g​r​a​v​i​t​y​ ​f​r​o​m​ ​h​e​r​e​.
			 * @param {string} name
			 */
			inFermentor: RequiredParams<'name'>
			/**
			 * L​o​g​ ​g​r​a​v​i​t​y​ ​→
			 */
			logGravity: string
			/**
			 * M​a​r​k​ ​F​e​r​m​e​n​t​i​n​g
			 */
			markFermenting: string
		}
		gravity: {
			/**
			 * G​r​a​v​i​t​y​ ​L​o​g​ ​—​ ​{​n​a​m​e​}
			 * @param {string} name
			 */
			title: RequiredParams<'name'>
			/**
			 * T​a​r​g​e​t​ ​O​G
			 */
			targetOg: string
			/**
			 * T​a​r​g​e​t​ ​F​G
			 */
			targetFg: string
			/**
			 * E​s​t​.​ ​A​B​V
			 */
			estAbv: string
			loadError: {
				/**
				 * C​o​u​l​d​n​'​t​ ​l​o​a​d​ ​g​r​a​v​i​t​y​ ​l​o​g
				 */
				title: string
				/**
				 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​ ​f​e​t​c​h​i​n​g​ ​t​h​i​s​ ​s​e​s​s​i​o​n​'​s​ ​r​e​a​d​i​n​g​s​.
				 */
				message: string
			}
			/**
			 * {​d​a​t​e​}​ ​—​ ​S​G​ ​{​s​g​}
			 * @param {string} date
			 * @param {string} sg
			 */
			entryLabel: RequiredParams<'date' | 'sg'>
			/**
			 * R​e​m​o​v​e
			 */
			remove: string
			/**
			 * S​G​ ​e​.​g​.​ ​1​.​0​4​2
			 */
			sgPlaceholder: string
			/**
			 * N​o​t​e​…
			 */
			notePlaceholder: string
			/**
			 * L​o​g
			 */
			log: string
		}
		hopSchedule: {
			/**
			 * N​o​ ​h​o​p​s​ ​r​e​c​o​r​d​e​d​.
			 */
			empty: string
			/**
			 * H​o​p​ ​A​d​d​i​t​i​o​n​ ​T​i​m​e​l​i​n​e
			 */
			title: string
			/**
			 * {​a​m​o​u​n​t​}​ ​{​u​n​i​t​}​ ​·​ ​{​u​s​e​}​ ​·​ ​{​a​l​p​h​a​}​%​ ​A​A
			 * @param {number} alpha
			 * @param {number} amount
			 * @param {string} unit
			 * @param {string} use
			 */
			detail: RequiredParams<'alpha' | 'amount' | 'unit' | 'use'>
		}
		yeastCalc: {
			/**
			 * Y​e​a​s​t​ ​P​i​t​c​h​ ​C​a​l​c​u​l​a​t​o​r
			 */
			title: string
			/**
			 * V​o​l​u​m​e​ ​(​g​a​l​)
			 */
			volumeLabel: string
			/**
			 * O​G
			 */
			ogLabel: string
			/**
			 * F​o​r​m
			 */
			formLabel: string
			/**
			 * L​i​q​u​i​d
			 */
			liquid: string
			/**
			 * D​r​y
			 */
			dry: string
			/**
			 * C​e​l​l​s​ ​n​e​e​d​e​d
			 */
			cellsNeeded: string
			/**
			 * P​a​c​k​a​g​e​s
			 */
			packages: string
			/**
			 * P​e​r​ ​p​a​c​k​a​g​e
			 */
			perPackage: string
		}
		page: {
			/**
			 * B​a​c​k​ ​t​o​ ​{​n​a​m​e​}
			 * @param {string} name
			 */
			backTo: RequiredParams<'name'>
			/**
			 * {​s​t​y​l​e​}​ ​·​ ​B​J​C​P​ ​{​c​o​d​e​}​ ​·​ ​{​s​i​z​e​}​ ​g​a​l
			 * @param {string} code
			 * @param {number} size
			 * @param {string} style
			 */
			styleBjcpBatch: RequiredParams<'code' | 'size' | 'style'>
			/**
			 * {​c​o​m​p​l​e​t​e​d​}​/​{​t​o​t​a​l​}​ ​s​t​e​p​s​ ​d​o​n​e
			 * @param {number} completed
			 * @param {number} total
			 */
			stepsDone: RequiredParams<'completed' | 'total'>
			/**
			 * B​a​t​c​h​ ​a​c​t​i​o​n​s
			 */
			batchActionsLabel: string
			/**
			 * C​a​n​c​e​l​ ​B​a​t​c​h
			 */
			cancelBatch: string
			/**
			 * D​e​l​e​t​e​ ​B​a​t​c​h
			 */
			deleteBatch: string
			cancelConfirm: {
				/**
				 * C​a​n​c​e​l​ ​b​a​t​c​h
				 */
				title: string
				/**
				 * C​a​n​c​e​l​ ​b​r​e​w​i​n​g
				 */
				messagePrefix: string
				/**
				 * ?​ ​T​h​i​s​ ​a​r​c​h​i​v​e​s​ ​t​h​e​ ​s​e​s​s​i​o​n​ ​—​ ​l​o​g​g​e​d​ ​s​t​e​p​s​ ​a​n​d​ ​g​r​a​v​i​t​y​ ​r​e​a​d​i​n​g​s​ ​a​r​e​ ​k​e​p​t​,​ ​b​u​t​ ​i​t​ ​m​o​v​e​s​ ​o​u​t​ ​o​f​ ​y​o​u​r​ ​a​c​t​i​v​e​ ​b​r​e​w​s​.
				 */
				messageSuffix: string
				/**
				 * K​e​e​p​ ​B​r​e​w​i​n​g
				 */
				keepBrewing: string
			}
			deleteConfirm: {
				/**
				 * D​e​l​e​t​e​ ​b​a​t​c​h
				 */
				title: string
				/**
				 * P​e​r​m​a​n​e​n​t​l​y​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​b​r​e​w​ ​s​e​s​s​i​o​n​ ​f​o​r
				 */
				messagePrefix: string
				/**
				 * ?​ ​A​l​l​ ​l​o​g​g​e​d​ ​s​t​e​p​s​ ​a​n​d​ ​g​r​a​v​i​t​y​ ​r​e​a​d​i​n​g​s​ ​w​i​l​l​ ​b​e​ ​l​o​s​t​.​ ​T​h​i​s​ ​c​a​n​'​t​ ​b​e​ ​u​n​d​o​n​e​.
				 */
				messageSuffix: string
			}
			notFound: {
				/**
				 * R​e​c​i​p​e​ ​n​o​t​ ​f​o​u​n​d
				 */
				title: string
				/**
				 * T​h​i​s​ ​r​e​c​i​p​e​ ​n​o​ ​l​o​n​g​e​r​ ​e​x​i​s​t​s​,​ ​o​r​ ​t​h​e​ ​l​i​n​k​ ​i​s​ ​i​n​v​a​l​i​d​.
				 */
				message: string
			}
			/**
			 * N​o​ ​b​r​e​w​ ​s​e​s​s​i​o​n​ ​y​e​t​ ​f​o​r
			 */
			noSessionPrefix: string
			/**
			 * .
			 */
			noSessionSuffix: string
			/**
			 * S​t​a​r​t​ ​B​r​e​w​i​n​g
			 */
			startBrewing: string
			tabs: {
				/**
				 * B​a​t​c​h
				 */
				batch: string
				/**
				 * G​r​a​v​i​t​y​ ​L​o​g
				 */
				gravity: string
				/**
				 * Y​e​a​s​t​ ​C​a​l​c
				 */
				yeast: string
				/**
				 * H​o​p​ ​S​c​h​e​d​u​l​e
				 */
				hops: string
			}
		}
	}
	conversions: {
		/**
		 * B​r​e​w​i​n​g​ ​c​a​l​c​u​l​a​t​o​r​s​ ​&​ ​u​n​i​t​ ​c​o​n​v​e​r​t​e​r​s
		 */
		subtitle: string
		tabs: {
			/**
			 * G​r​a​v​i​t​y
			 */
			gravity: string
			/**
			 * T​e​m​p​e​r​a​t​u​r​e
			 */
			temperature: string
			/**
			 * V​o​l​u​m​e
			 */
			volume: string
			/**
			 * W​e​i​g​h​t
			 */
			weight: string
			/**
			 * A​B​V​/​A​B​W
			 */
			abv: string
			/**
			 * C​o​l​o​r
			 */
			color: string
			/**
			 * W​a​t​e​r
			 */
			water: string
		}
		abv: {
			/**
			 * A​B​V​ ​/​ ​A​B​W
			 */
			title: string
			/**
			 * O​r​i​g​i​n​a​l​ ​G​r​a​v​i​t​y
			 */
			ogLabel: string
			/**
			 * F​i​n​a​l​ ​G​r​a​v​i​t​y
			 */
			fgLabel: string
			/**
			 * A​B​V
			 */
			abv: string
			/**
			 * A​B​W
			 */
			abw: string
			/**
			 * A​t​t​e​n​u​a​t​i​o​n
			 */
			attenuation: string
		}
		color: {
			/**
			 * C​o​l​o​r
			 */
			title: string
			/**
			 * A​p​p​r​o​x​i​m​a​t​e​ ​b​e​e​r​ ​c​o​l​o​r
			 */
			approxColor: string
			/**
			 * S​R​M
			 */
			srmLabel: string
			/**
			 * E​B​C
			 */
			ebcLabel: string
			/**
			 * L​o​v​i​b​o​n​d
			 */
			lovibondLabel: string
			/**
			 * S​R​M​ ​R​e​f​e​r​e​n​c​e
			 */
			reference: string
			/**
			 * S​R​M​ ​{​v​a​l​u​e​}
			 * @param {number} value
			 */
			srmTitle: RequiredParams<'value'>
		}
		gravity: {
			/**
			 * G​r​a​v​i​t​y​ ​C​o​n​v​e​r​s​i​o​n​s
			 */
			title: string
			/**
			 * S​p​e​c​i​f​i​c​ ​G​r​a​v​i​t​y
			 */
			sgLabel: string
			/**
			 * D​e​g​r​e​e​s​ ​P​l​a​t​o
			 */
			platoLabel: string
			/**
			 * B​r​i​x
			 */
			brixLabel: string
			/**
			 * R​e​f​e​r​e​n​c​e​:
			 */
			reference: string
			/**
			 * O​G​ ​1​.​0​0​0​ ​=​ ​0​°​P​ ​·​ ​1​.​0​4​0​ ​=​ ​1​0​°​P​ ​·​ ​1​.​0​6​0​ ​=​ ​1​4​.​7​°​P​ ​·​ ​1​.​0​8​0​ ​=​ ​1​9​.​3​°​P​ ​·​ ​1​.​1​0​0​ ​=​ ​2​3​.​8​°​P
			 */
			referenceBody: string
		}
		temperature: {
			/**
			 * T​e​m​p​e​r​a​t​u​r​e
			 */
			title: string
			/**
			 * F​a​h​r​e​n​h​e​i​t
			 */
			fahrenheitLabel: string
			/**
			 * C​e​l​s​i​u​s
			 */
			celsiusLabel: string
			presets: {
				/**
				 * M​a​s​h
				 */
				mash: string
				/**
				 * S​p​a​r​g​e
				 */
				sparge: string
				/**
				 * P​i​t​c​h​ ​A​l​e
				 */
				pitchAle: string
				/**
				 * P​i​t​c​h​ ​L​a​g​e​r
				 */
				pitchLager: string
				/**
				 * F​e​r​m​e​n​t
				 */
				ferment: string
			}
			/**
			 * {​l​a​b​e​l​}​ ​(​{​t​e​m​p​}​°​F​)
			 * @param {string} label
			 * @param {number} temp
			 */
			presetButton: RequiredParams<'label' | 'temp'>
		}
		volume: {
			/**
			 * V​o​l​u​m​e
			 */
			title: string
			/**
			 * G​a​l​l​o​n​s
			 */
			gallonsLabel: string
			/**
			 * L​i​t​r​e​s
			 */
			litresLabel: string
			/**
			 * Q​u​a​r​t​s
			 */
			quartsLabel: string
			/**
			 * M​i​l​l​i​l​i​t​r​e​s
			 */
			millilitresLabel: string
		}
		weight: {
			/**
			 * W​e​i​g​h​t
			 */
			title: string
			/**
			 * P​o​u​n​d​s
			 */
			poundsLabel: string
			/**
			 * O​u​n​c​e​s
			 */
			ouncesLabel: string
			/**
			 * K​i​l​o​g​r​a​m​s
			 */
			kilogramsLabel: string
			/**
			 * G​r​a​m​s
			 */
			gramsLabel: string
		}
		water: {
			/**
			 * W​a​t​e​r​ ​C​h​e​m​i​s​t​r​y
			 */
			title: string
			/**
			 * V​o​l​u​m​e​ ​(​g​a​l​)
			 */
			volumeLabel: string
			/**
			 * p​H​ ​T​a​r​g​e​t
			 */
			phTargetLabel: string
			/**
			 * S​O​₄​:​C​l​ ​R​a​t​i​o​ ​·
			 */
			ratioLabel: string
			profile: {
				/**
				 * H​o​p​p​y​ ​/​ ​B​i​t​t​e​r
				 */
				hoppy: string
				/**
				 * B​a​l​a​n​c​e​d​ ​H​o​p​p​y
				 */
				balancedHoppy: string
				/**
				 * B​a​l​a​n​c​e​d
				 */
				balanced: string
				/**
				 * M​a​l​t​y​ ​/​ ​S​o​f​t
				 */
				malty: string
			}
		}
	}
	login: {
		/**
		 * S​i​g​n​ ​i​n​ ​t​o​ ​y​o​u​r​ ​b​r​e​w​e​r​y
		 */
		tagline: string
		/**
		 * U​s​e​r​n​a​m​e
		 */
		usernameLabel: string
		/**
		 * y​o​u​@​b​r​e​w​e​r​y​.​c​o​m
		 */
		usernamePlaceholder: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		passwordLabel: string
		/**
		 * R​e​m​e​m​b​e​r​ ​m​e
		 */
		rememberMe: string
		/**
		 * S​i​g​n​ ​i​n
		 */
		signIn: string
		/**
		 * s​i​g​n​-​i​n​ ​f​a​i​l​e​d
		 */
		signInFailed: string
		/**
		 * M​O​S​T​O​ ​·​ ​B​R​E​W​I​N​G​ ​C​O​M​P​A​N​I​O​N
		 */
		footer: string
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Edit
		 */
		edit: () => LocalizedString
		/**
		 * Delete
		 */
		'delete': () => LocalizedString
		/**
		 * Required
		 */
		required: () => LocalizedString
		/**
		 * Something went wrong.
		 */
		somethingWrong: () => LocalizedString
	}
	nav: {
		/**
		 * Dashboard
		 */
		dashboard: () => LocalizedString
		/**
		 * Recipes
		 */
		recipes: () => LocalizedString
		/**
		 * Inventory
		 */
		inventory: () => LocalizedString
		/**
		 * Equipment
		 */
		equipment: () => LocalizedString
		/**
		 * Conversions
		 */
		conversions: () => LocalizedString
		/**
		 * Expand sidebar
		 */
		expandSidebar: () => LocalizedString
		/**
		 * Collapse sidebar
		 */
		collapseSidebar: () => LocalizedString
		/**
		 * Sign out
		 */
		signOut: () => LocalizedString
		/**
		 * Language
		 */
		language: () => LocalizedString
	}
	dashboard: {
		loadError: {
			/**
			 * Couldn't load your dashboard
			 */
			title: () => LocalizedString
			/**
			 * Something went wrong fetching your data. Try refreshing the page.
			 */
			message: () => LocalizedString
		}
		stats: {
			/**
			 * Recipes
			 */
			recipes: () => LocalizedString
			/**
			 * All-grain
			 */
			allGrain: () => LocalizedString
			/**
			 * Total Batches
			 */
			totalBatches: () => LocalizedString
			/**
			 * {count} completed
			 */
			completedCount: (arg: { count: number }) => LocalizedString
			/**
			 * Inventory Items
			 */
			inventoryItems: () => LocalizedString
			/**
			 * {count} low stock
			 */
			lowStockCount: (arg: { count: number }) => LocalizedString
			/**
			 * Well stocked
			 */
			wellStocked: () => LocalizedString
			/**
			 * Active Brew
			 */
			activeBrew: () => LocalizedString
			/**
			 * Active Brews
			 */
			activeBrews: () => LocalizedString
			/**
			 * None
			 */
			activeBrewNone: () => LocalizedString
			/**
			 * Day {day}
			 */
			activeBrewDay: (arg: { day: number }) => LocalizedString
			/**
			 * {count} Brewing
			 */
			activeBrewing: (arg: { count: number }) => LocalizedString
			/**
			 * +{count} more
			 */
			moreRecipes: (arg: { count: number }) => LocalizedString
		}
		activeBrewCard: {
			/**
			 * Open →
			 */
			open: () => LocalizedString
			/**
			 *  · Day {day} of {status}
			 */
			dayOfStatus: (arg: { day: number, status: string }) => LocalizedString
			/**
			 *  · {status}
			 */
			statusOnly: (arg: { status: string }) => LocalizedString
			/**
			 * Fermentation progress
			 */
			fermentationProgress: () => LocalizedString
			/**
			 * OG
			 */
			og: () => LocalizedString
			/**
			 * Current
			 */
			current: () => LocalizedString
			/**
			 * Target FG
			 */
			targetFg: () => LocalizedString
			/**
			 * Temp
			 */
			temp: () => LocalizedString
		}
		lowStock: {
			/**
			 * Low Stock
			 */
			title: () => LocalizedString
		}
		quickActions: {
			/**
			 * Quick Actions
			 */
			title: () => LocalizedString
			/**
			 * New Recipe
			 */
			newRecipe: () => LocalizedString
			/**
			 * Continue Brewing
			 */
			continueBrewing: () => LocalizedString
			/**
			 * Start Brew Day
			 */
			startBrewDay: () => LocalizedString
		}
		recentRecipes: {
			/**
			 * Recent Recipes
			 */
			title: () => LocalizedString
			/**
			 * View all
			 */
			viewAll: () => LocalizedString
			/**
			 * No recipes yet — create one to get started.
			 */
			empty: () => LocalizedString
			/**
			 * ABV
			 */
			abv: () => LocalizedString
			/**
			 * IBU
			 */
			ibu: () => LocalizedString
		}
	}
	equipment: {
		/**
		 * Equipment actions
		 */
		actionsLabel: () => LocalizedString
		/**
		 * New Equipment
		 */
		newEquipment: () => LocalizedString
		notFound: {
			/**
			 * Equipment not found
			 */
			name: () => LocalizedString
			/**
			 * It may have been deleted
			 */
			type: () => LocalizedString
			/**
			 * This equipment no longer exists, or the link is invalid.
			 */
			message: () => LocalizedString
		}
		saveError: {
			/**
			 * Couldn't save
			 */
			title: () => LocalizedString
			/**
			 * Could not save this equipment
			 */
			generic: () => LocalizedString
		}
		condition: {
			/**
			 * Good
			 */
			good: () => LocalizedString
			/**
			 * Fair
			 */
			fair: () => LocalizedString
			/**
			 * Poor
			 */
			poor: () => LocalizedString
		}
		form: {
			/**
			 * Name
			 */
			nameLabel: () => LocalizedString
			/**
			 * Type
			 */
			typeLabel: () => LocalizedString
			/**
			 * Condition
			 */
			conditionLabel: () => LocalizedString
			/**
			 * Capacity
			 */
			capacityLabel: () => LocalizedString
			/**
			 * e.g. 10 gal
			 */
			capacityPlaceholder: () => LocalizedString
			/**
			 * Material
			 */
			materialLabel: () => LocalizedString
			/**
			 * e.g. Stainless Steel
			 */
			materialPlaceholder: () => LocalizedString
			/**
			 * Notes
			 */
			notesLabel: () => LocalizedString
			/**
			 * Save changes
			 */
			saveChanges: () => LocalizedString
			/**
			 * Add equipment
			 */
			addEquipment: () => LocalizedString
		}
		list: {
			/**
			 * Equipment
			 */
			title: () => LocalizedString
			/**
			 * Add Equipment
			 */
			addButton: () => LocalizedString
			/**
			 * All
			 */
			all: () => LocalizedString
			loadError: {
				/**
				 * Couldn't load equipment
				 */
				title: () => LocalizedString
				/**
				 * Something went wrong fetching your equipment. Try refreshing the page.
				 */
				message: () => LocalizedString
			}
			/**
			 * No equipment yet — add some to get started.
			 */
			empty: () => LocalizedString
			/**
			 * No equipment matches this filter.
			 */
			emptyFiltered: () => LocalizedString
		}
		deleteConfirm: {
			/**
			 * Delete equipment
			 */
			title: () => LocalizedString
			/**
			 * Delete
			 */
			messagePrefix: () => LocalizedString
			/**
			 * ? This can't be undone.
			 */
			messageSuffix: () => LocalizedString
		}
		deleteError: {
			/**
			 * Couldn't delete equipment
			 */
			title: () => LocalizedString
		}
	}
	inventory: {
		/**
		 * Item actions
		 */
		actionsLabel: () => LocalizedString
		/**
		 * New Item
		 */
		newItem: () => LocalizedString
		itemNotFound: {
			/**
			 * Item not found
			 */
			name: () => LocalizedString
			/**
			 * It may have been deleted
			 */
			subtitle: () => LocalizedString
			/**
			 * This item no longer exists, or the link is invalid.
			 */
			message: () => LocalizedString
		}
		saveError: {
			/**
			 * Couldn't save
			 */
			title: () => LocalizedString
			/**
			 * Could not save this item
			 */
			generic: () => LocalizedString
		}
		category: {
			/**
			 * Grains
			 */
			grain: () => LocalizedString
			/**
			 * Hops
			 */
			hop: () => LocalizedString
			/**
			 * Yeast
			 */
			yeast: () => LocalizedString
			/**
			 * Adjuncts
			 */
			adjunct: () => LocalizedString
			/**
			 * Water Chem
			 */
			water_chem: () => LocalizedString
			/**
			 * Packaging
			 */
			packaging: () => LocalizedString
		}
		status: {
			/**
			 * Out of stock
			 */
			out: () => LocalizedString
			/**
			 * Low
			 */
			low: () => LocalizedString
			/**
			 * In stock
			 */
			ok: () => LocalizedString
		}
		expiry: {
			/**
			 * Expired
			 */
			expired: () => LocalizedString
			/**
			 * {days}d
			 */
			daysShort: (arg: { days: number }) => LocalizedString
		}
		/**
		 * {alpha}% AA · {form}
		 */
		hopMeta: (arg: { alpha: number, form: string }) => LocalizedString
		form: {
			/**
			 * Category
			 */
			categoryLabel: () => LocalizedString
			/**
			 * Name
			 */
			nameLabel: () => LocalizedString
			/**
			 * e.g. {category}
			 */
			namePlaceholder: (arg: { category: string }) => LocalizedString
			/**
			 * Amount
			 */
			amountLabel: () => LocalizedString
			/**
			 * Unit
			 */
			unitLabel: () => LocalizedString
			/**
			 * Low stock threshold
			 */
			lowThresholdLabel: () => LocalizedString
			/**
			 * Optional
			 */
			optional: () => LocalizedString
			/**
			 * Expiry
			 */
			expiryLabel: () => LocalizedString
			/**
			 * Alpha acid %
			 */
			alphaLabel: () => LocalizedString
			/**
			 * Form
			 */
			formLabel: () => LocalizedString
			/**
			 * Attenuation
			 */
			attenuationLabel: () => LocalizedString
			/**
			 * e.g. 73-77%
			 */
			attenuationPlaceholder: () => LocalizedString
			/**
			 * Brand
			 */
			brandLabel: () => LocalizedString
			/**
			 * Save changes
			 */
			saveChanges: () => LocalizedString
			/**
			 * Add item
			 */
			addItem: () => LocalizedString
		}
		list: {
			/**
			 * Inventory
			 */
			title: () => LocalizedString
			/**
			 * {count} items on hand
			 */
			itemsOnHand: (arg: { count: number }) => LocalizedString
			/**
			 * Add Item
			 */
			addButton: () => LocalizedString
			/**
			 * {count} items low or out of stock
			 */
			lowStockWarning: (arg: { count: number }) => LocalizedString
			/**
			 * Search {category}…
			 */
			searchPlaceholder: (arg: { category: string }) => LocalizedString
			loadError: {
				/**
				 * Couldn't load inventory
				 */
				title: () => LocalizedString
				/**
				 * Something went wrong fetching your inventory. Try refreshing the page.
				 */
				message: () => LocalizedString
			}
			/**
			 * No items yet — add one to get started.
			 */
			empty: () => LocalizedString
			/**
			 * No items match your search.
			 */
			emptySearch: () => LocalizedString
		}
		table: {
			/**
			 * Name
			 */
			name: () => LocalizedString
			/**
			 * Alpha
			 */
			alpha: () => LocalizedString
			/**
			 * Type
			 */
			type: () => LocalizedString
			/**
			 * Brand
			 */
			brand: () => LocalizedString
			/**
			 * Amount
			 */
			amount: () => LocalizedString
			/**
			 * Expiry
			 */
			expiry: () => LocalizedString
			/**
			 * Status
			 */
			status: () => LocalizedString
		}
		deleteConfirm: {
			/**
			 * Delete item
			 */
			title: () => LocalizedString
			/**
			 * Delete
			 */
			messagePrefix: () => LocalizedString
			/**
			 * ? This can't be undone.
			 */
			messageSuffix: () => LocalizedString
		}
		deleteError: {
			/**
			 * Couldn't delete item
			 */
			title: () => LocalizedString
		}
	}
	recipes: {
		/**
		 * Recipe actions
		 */
		actionsLabel: () => LocalizedString
		/**
		 * New Recipe
		 */
		newRecipe: () => LocalizedString
		/**
		 * Brewing
		 */
		brewingBadge: () => LocalizedString
		/**
		 * {style} · BJCP {code}
		 */
		styleBjcp: (arg: { code: string, style: string }) => LocalizedString
		/**
		 * {size} gal
		 */
		batchSize: (arg: { size: number }) => LocalizedString
		/**
		 * Last brewed {date}
		 */
		lastBrewed: (arg: { date: string }) => LocalizedString
		actions: {
			/**
			 * Resume Brewing
			 */
			resumeBrewing: () => LocalizedString
			/**
			 * Start Brewing
			 */
			startBrewing: () => LocalizedString
			/**
			 * Clone
			 */
			clone: () => LocalizedString
			/**
			 * Export BeerXML
			 */
			exportBeerXml: () => LocalizedString
		}
		stats: {
			/**
			 * ABV
			 */
			abv: () => LocalizedString
			/**
			 * IBU
			 */
			ibu: () => LocalizedString
			/**
			 * OG
			 */
			og: () => LocalizedString
			/**
			 * FG
			 */
			fg: () => LocalizedString
			/**
			 * SRM
			 */
			srm: () => LocalizedString
			/**
			 * EFF
			 */
			eff: () => LocalizedString
		}
		notFound: {
			/**
			 * Recipe not found
			 */
			name: () => LocalizedString
			/**
			 * It may have been deleted
			 */
			subtitle: () => LocalizedString
			/**
			 * This recipe no longer exists, or the link is invalid.
			 */
			message: () => LocalizedString
		}
		/**
		 * Couldn't start brewing
		 */
		startBrewingError: () => LocalizedString
		/**
		 * Couldn't clone recipe
		 */
		cloneError: () => LocalizedString
		/**
		 *  (Copy)
		 */
		cloneSuffix: () => LocalizedString
		deleteConfirm: {
			/**
			 * Delete recipe
			 */
			title: () => LocalizedString
			/**
			 * Delete
			 */
			messagePrefix: () => LocalizedString
			/**
			 * ? This can't be undone.
			 */
			messageSuffix: () => LocalizedString
		}
		deleteError: {
			/**
			 * Couldn't delete recipe
			 */
			title: () => LocalizedString
		}
		list: {
			/**
			 * Recipes
			 */
			title: () => LocalizedString
			/**
			 * {count} all-grain recipes
			 */
			subtitle: (arg: { count: number }) => LocalizedString
			/**
			 * + New Recipe
			 */
			newRecipeCta: () => LocalizedString
			/**
			 * Import BeerXML
			 */
			importBeerXml: () => LocalizedString
			/**
			 * Search recipes…
			 */
			searchPlaceholder: () => LocalizedString
			sort: {
				/**
				 * Sort: Name
				 */
				name: () => LocalizedString
				/**
				 * Sort: Recent
				 */
				recent: () => LocalizedString
				/**
				 * Sort: ABV
				 */
				abv: () => LocalizedString
				/**
				 * Sort: IBU
				 */
				ibu: () => LocalizedString
			}
			/**
			 * Import failed
			 */
			importFailed: () => LocalizedString
			/**
			 * Could not import that recipe
			 */
			importGenericError: () => LocalizedString
			/**
			 * Could not read that BeerXML file
			 */
			readError: () => LocalizedString
			loadError: {
				/**
				 * Couldn't load recipes
				 */
				title: () => LocalizedString
				/**
				 * Something went wrong fetching your recipes. Try refreshing the page.
				 */
				message: () => LocalizedString
			}
			/**
			 * No recipes yet — create one to get started.
			 */
			empty: () => LocalizedString
			/**
			 * No recipes match your search.
			 */
			emptySearch: () => LocalizedString
		}
		detail: {
			/**
			 * Process
			 */
			process: () => LocalizedString
			/**
			 * Mash Temp
			 */
			mashTemp: () => LocalizedString
			/**
			 * Mash Time
			 */
			mashTime: () => LocalizedString
			/**
			 * Boil Time
			 */
			boilTime: () => LocalizedString
			/**
			 * Yeast
			 */
			yeast: () => LocalizedString
			/**
			 * Ferm Temp
			 */
			fermTemp: () => LocalizedString
			/**
			 * Attenuation
			 */
			attenuation: () => LocalizedString
			/**
			 * Yeast Strain
			 */
			yeastStrain: () => LocalizedString
			/**
			 * No grains recorded.
			 */
			noGrains: () => LocalizedString
			/**
			 * Grain bill — {total} lb total
			 */
			grainBill: (arg: { total: string }) => LocalizedString
			/**
			 * No hops recorded.
			 */
			noHops: () => LocalizedString
			/**
			 * Hop schedule
			 */
			hopSchedule: () => LocalizedString
			/**
			 * min
			 */
			min: () => LocalizedString
			/**
			 * {use} · {alpha}% AA
			 */
			hopUseAlpha: (arg: { alpha: number, use: string }) => LocalizedString
			/**
			 * No water profile recorded.
			 */
			noWater: () => LocalizedString
			/**
			 * Water profile
			 */
			waterProfile: () => LocalizedString
			/**
			 * Strike Water
			 */
			strikeWater: () => LocalizedString
			tabs: {
				/**
				 * Overview
				 */
				overview: () => LocalizedString
				/**
				 * Grains
				 */
				grains: () => LocalizedString
				/**
				 * Hops
				 */
				hops: () => LocalizedString
				/**
				 * Water
				 */
				water: () => LocalizedString
				/**
				 * Notes
				 */
				notes: () => LocalizedString
			}
			/**
			 * Scale Batch
			 */
			scaleBatch: () => LocalizedString
			/**
			 * ×{factor} of original recipe
			 */
			scaleFactor: (arg: { factor: string }) => LocalizedString
			/**
			 * No notes recorded.
			 */
			noNotes: () => LocalizedString
		}
		form: {
			/**
			 * Name
			 */
			nameLabel: () => LocalizedString
			/**
			 * Style
			 */
			styleLabel: () => LocalizedString
			/**
			 * BJCP code
			 */
			bjcpCodeLabel: () => LocalizedString
			/**
			 * BJCP {code}
			 */
			bjcpFragment: (arg: { code: string }) => LocalizedString
			/**
			 * Style · BJCP code
			 */
			styleBjcpPlaceholder: () => LocalizedString
			/**
			 * Batch size (gal)
			 */
			batchSizeLabel: () => LocalizedString
			/**
			 * Boil time (min)
			 */
			boilTimeLabel: () => LocalizedString
			/**
			 * OG
			 */
			ogLabel: () => LocalizedString
			/**
			 * FG
			 */
			fgLabel: () => LocalizedString
			/**
			 * ABV %
			 */
			abvLabel: () => LocalizedString
			/**
			 * IBU
			 */
			ibuLabel: () => LocalizedString
			/**
			 * SRM
			 */
			srmLabel: () => LocalizedString
			/**
			 * Efficiency %
			 */
			efficiencyLabel: () => LocalizedString
			/**
			 * Tags
			 */
			tagsLabel: () => LocalizedString
			/**
			 * Comma-separated
			 */
			tagsDescription: () => LocalizedString
			/**
			 * Notes
			 */
			notesLabel: () => LocalizedString
			/**
			 * Save changes
			 */
			saveChanges: () => LocalizedString
			/**
			 * Create recipe
			 */
			createRecipe: () => LocalizedString
			saveError: {
				/**
				 * Couldn't save
				 */
				title: () => LocalizedString
				/**
				 * Could not save this recipe
				 */
				generic: () => LocalizedString
			}
		}
	}
	brewday: {
		steps: {
			phases: {
				/**
				 * Prep
				 */
				prep: () => LocalizedString
				/**
				 * Mash
				 */
				mash: () => LocalizedString
				/**
				 * Lauter
				 */
				lauter: () => LocalizedString
				/**
				 * Boil
				 */
				boil: () => LocalizedString
				/**
				 * Chill
				 */
				chill: () => LocalizedString
				/**
				 * Ferment
				 */
				ferment: () => LocalizedString
			}
			review: {
				/**
				 * Review Recipe & Gather Equipment
				 */
				label: () => LocalizedString
				/**
				 * Batch: {size} gal · Efficiency: {eff}%
				 */
				detail: (arg: { eff: number, size: number }) => LocalizedString
			}
			millGrain: {
				/**
				 * Mill Grain
				 */
				label: () => LocalizedString
				/**
				 * Total grain: {total} lb — set gap to 0.040"
				 */
				detailWithGrain: (arg: { total: string }) => LocalizedString
				/**
				 * No grain bill recorded
				 */
				detailNoGrain: () => LocalizedString
			}
			heatStrike: {
				/**
				 * Heat Strike Water
				 */
				label: () => LocalizedString
				/**
				 * Heat {vol} gal to {temp}°F
				 */
				detail: (arg: { temp: number, vol: string }) => LocalizedString
				/**
				 * No water profile / mash schedule recorded
				 */
				noData: () => LocalizedString
			}
			mashIn: {
				/**
				 * Mash In
				 */
				label: () => LocalizedString
				/**
				 * Target mash temp: {temp}°F — stir well
				 */
				detail: (arg: { temp: number }) => LocalizedString
				/**
				 * No mash schedule recorded
				 */
				noSchedule: () => LocalizedString
			}
			mashRest: {
				/**
				 * Mash Rest
				 */
				label: () => LocalizedString
				/**
				 * Hold at {temp}°F — check temp every 15 min
				 */
				detail: (arg: { temp: number }) => LocalizedString
			}
			vorlauf: {
				/**
				 * Vorlauf
				 */
				label: () => LocalizedString
				/**
				 * Recirculate until runoff runs clear (~2 qt)
				 */
				detail: () => LocalizedString
			}
			sparge: {
				/**
				 * Sparge & Collect Wort
				 */
				label: () => LocalizedString
				/**
				 * Collect {vol} gal pre-boil wort
				 */
				detail: (arg: { vol: string }) => LocalizedString
				/**
				 * No water profile recorded
				 */
				noProfile: () => LocalizedString
			}
			bringToBoil: {
				/**
				 * Bring to Boil
				 */
				label: () => LocalizedString
				/**
				 * Watch for hot break and boil-over
				 */
				detail: () => LocalizedString
			}
			/**
			 * Flameout — {name}
			 */
			flameout: (arg: { name: string }) => LocalizedString
			/**
			 * Hop Addition — {name}
			 */
			hopAddition: (arg: { name: string }) => LocalizedString
			/**
			 * {amount} {unit} {name} · @{time} min · {alpha}% AA
			 */
			hopDetail: (arg: { alpha: number, amount: number, name: string, time: number, unit: string }) => LocalizedString
			chillWort: {
				/**
				 * Chill Wort to Pitch Temp
				 */
				label: () => LocalizedString
				/**
				 * Target: {temp}°F — sanitize fermentor while chilling
				 */
				detail: (arg: { temp: string }) => LocalizedString
			}
			/**
			 * No yeast recorded
			 */
			noYeastRecorded: () => LocalizedString
			transfer: {
				/**
				 * Transfer to Fermentor
				 */
				label: () => LocalizedString
				/**
				 * Measure OG (target: {og}) and take refractometer reading
				 */
				detail: (arg: { og: number }) => LocalizedString
			}
			pitchYeast: {
				/**
				 * Pitch Yeast
				 */
				label: () => LocalizedString
				/**
				 * {name} — ferment at {range}
				 */
				detail: (arg: { name: string, range: string }) => LocalizedString
			}
			seal: {
				/**
				 * Seal & Attach Airlock
				 */
				label: () => LocalizedString
				/**
				 * Fill airlock with sanitizer, label fermentor with date
				 */
				detail: () => LocalizedString
			}
		}
		stepsList: {
			/**
			 * Now
			 */
			now: () => LocalizedString
		}
		timeline: {
			/**
			 * Batch Timeline
			 */
			title: () => LocalizedString
			/**
			 * of {total} planned
			 */
			ofPlanned: (arg: { total: string }) => LocalizedString
		}
		nowCard: {
			/**
			 * Now · {phase}
			 */
			nowInPhase: (arg: { phase: string }) => LocalizedString
			/**
			 * Time's up
			 */
			timesUp: () => LocalizedString
			/**
			 * over planned time
			 */
			overPlanned: () => LocalizedString
			/**
			 * of {duration}
			 */
			ofDuration: (arg: { duration: string }) => LocalizedString
			/**
			 *  · paused
			 */
			paused: () => LocalizedString
			/**
			 * No timer — confirm when done
			 */
			noTimer: () => LocalizedString
			/**
			 * Start {duration} timer
			 */
			startTimer: (arg: { duration: string }) => LocalizedString
			/**
			 * Pause
			 */
			pause: () => LocalizedString
			/**
			 * Resume
			 */
			resume: () => LocalizedString
			/**
			 * +5m
			 */
			plus5: () => LocalizedString
			/**
			 * Done — next: {label} →
			 */
			doneNext: (arg: { label: string }) => LocalizedString
			/**
			 * Done — finish brew day →
			 */
			doneFinish: () => LocalizedString
			/**
			 * Waiting for your confirmation — add time if you need it.
			 */
			waitingConfirm: () => LocalizedString
			/**
			 * Next timer ({duration}) starts automatically after you confirm.
			 */
			nextTimerStarts: (arg: { duration: string }) => LocalizedString
			/**
			 * Next step has no timer.
			 */
			nextNoTimer: () => LocalizedString
			/**
			 * Last step of the batch.
			 */
			lastStep: () => LocalizedString
		}
		sidebarWidget: {
			/**
			 * Brewing
			 */
			title: () => LocalizedString
			/**
			 * {completed} of {total} steps done
			 */
			stepsDone: (arg: { completed: number, total: number }) => LocalizedString
		}
		completion: {
			/**
			 * Brew Day Complete
			 */
			title: () => LocalizedString
			/**
			 * All {count} steps done
			 */
			allStepsDone: (arg: { count: number }) => LocalizedString
			/**
			 * {name} is in the fermentor. Log your OG and track gravity from here.
			 */
			inFermentor: (arg: { name: string }) => LocalizedString
			/**
			 * Log gravity →
			 */
			logGravity: () => LocalizedString
			/**
			 * Mark Fermenting
			 */
			markFermenting: () => LocalizedString
		}
		gravity: {
			/**
			 * Gravity Log — {name}
			 */
			title: (arg: { name: string }) => LocalizedString
			/**
			 * Target OG
			 */
			targetOg: () => LocalizedString
			/**
			 * Target FG
			 */
			targetFg: () => LocalizedString
			/**
			 * Est. ABV
			 */
			estAbv: () => LocalizedString
			loadError: {
				/**
				 * Couldn't load gravity log
				 */
				title: () => LocalizedString
				/**
				 * Something went wrong fetching this session's readings.
				 */
				message: () => LocalizedString
			}
			/**
			 * {date} — SG {sg}
			 */
			entryLabel: (arg: { date: string, sg: string }) => LocalizedString
			/**
			 * Remove
			 */
			remove: () => LocalizedString
			/**
			 * SG e.g. 1.042
			 */
			sgPlaceholder: () => LocalizedString
			/**
			 * Note…
			 */
			notePlaceholder: () => LocalizedString
			/**
			 * Log
			 */
			log: () => LocalizedString
		}
		hopSchedule: {
			/**
			 * No hops recorded.
			 */
			empty: () => LocalizedString
			/**
			 * Hop Addition Timeline
			 */
			title: () => LocalizedString
			/**
			 * {amount} {unit} · {use} · {alpha}% AA
			 */
			detail: (arg: { alpha: number, amount: number, unit: string, use: string }) => LocalizedString
		}
		yeastCalc: {
			/**
			 * Yeast Pitch Calculator
			 */
			title: () => LocalizedString
			/**
			 * Volume (gal)
			 */
			volumeLabel: () => LocalizedString
			/**
			 * OG
			 */
			ogLabel: () => LocalizedString
			/**
			 * Form
			 */
			formLabel: () => LocalizedString
			/**
			 * Liquid
			 */
			liquid: () => LocalizedString
			/**
			 * Dry
			 */
			dry: () => LocalizedString
			/**
			 * Cells needed
			 */
			cellsNeeded: () => LocalizedString
			/**
			 * Packages
			 */
			packages: () => LocalizedString
			/**
			 * Per package
			 */
			perPackage: () => LocalizedString
		}
		page: {
			/**
			 * Back to {name}
			 */
			backTo: (arg: { name: string }) => LocalizedString
			/**
			 * {style} · BJCP {code} · {size} gal
			 */
			styleBjcpBatch: (arg: { code: string, size: number, style: string }) => LocalizedString
			/**
			 * {completed}/{total} steps done
			 */
			stepsDone: (arg: { completed: number, total: number }) => LocalizedString
			/**
			 * Batch actions
			 */
			batchActionsLabel: () => LocalizedString
			/**
			 * Cancel Batch
			 */
			cancelBatch: () => LocalizedString
			/**
			 * Delete Batch
			 */
			deleteBatch: () => LocalizedString
			cancelConfirm: {
				/**
				 * Cancel batch
				 */
				title: () => LocalizedString
				/**
				 * Cancel brewing
				 */
				messagePrefix: () => LocalizedString
				/**
				 * ? This archives the session — logged steps and gravity readings are kept, but it moves out of your active brews.
				 */
				messageSuffix: () => LocalizedString
				/**
				 * Keep Brewing
				 */
				keepBrewing: () => LocalizedString
			}
			deleteConfirm: {
				/**
				 * Delete batch
				 */
				title: () => LocalizedString
				/**
				 * Permanently delete this brew session for
				 */
				messagePrefix: () => LocalizedString
				/**
				 * ? All logged steps and gravity readings will be lost. This can't be undone.
				 */
				messageSuffix: () => LocalizedString
			}
			notFound: {
				/**
				 * Recipe not found
				 */
				title: () => LocalizedString
				/**
				 * This recipe no longer exists, or the link is invalid.
				 */
				message: () => LocalizedString
			}
			/**
			 * No brew session yet for
			 */
			noSessionPrefix: () => LocalizedString
			/**
			 * .
			 */
			noSessionSuffix: () => LocalizedString
			/**
			 * Start Brewing
			 */
			startBrewing: () => LocalizedString
			tabs: {
				/**
				 * Batch
				 */
				batch: () => LocalizedString
				/**
				 * Gravity Log
				 */
				gravity: () => LocalizedString
				/**
				 * Yeast Calc
				 */
				yeast: () => LocalizedString
				/**
				 * Hop Schedule
				 */
				hops: () => LocalizedString
			}
		}
	}
	conversions: {
		/**
		 * Brewing calculators & unit converters
		 */
		subtitle: () => LocalizedString
		tabs: {
			/**
			 * Gravity
			 */
			gravity: () => LocalizedString
			/**
			 * Temperature
			 */
			temperature: () => LocalizedString
			/**
			 * Volume
			 */
			volume: () => LocalizedString
			/**
			 * Weight
			 */
			weight: () => LocalizedString
			/**
			 * ABV/ABW
			 */
			abv: () => LocalizedString
			/**
			 * Color
			 */
			color: () => LocalizedString
			/**
			 * Water
			 */
			water: () => LocalizedString
		}
		abv: {
			/**
			 * ABV / ABW
			 */
			title: () => LocalizedString
			/**
			 * Original Gravity
			 */
			ogLabel: () => LocalizedString
			/**
			 * Final Gravity
			 */
			fgLabel: () => LocalizedString
			/**
			 * ABV
			 */
			abv: () => LocalizedString
			/**
			 * ABW
			 */
			abw: () => LocalizedString
			/**
			 * Attenuation
			 */
			attenuation: () => LocalizedString
		}
		color: {
			/**
			 * Color
			 */
			title: () => LocalizedString
			/**
			 * Approximate beer color
			 */
			approxColor: () => LocalizedString
			/**
			 * SRM
			 */
			srmLabel: () => LocalizedString
			/**
			 * EBC
			 */
			ebcLabel: () => LocalizedString
			/**
			 * Lovibond
			 */
			lovibondLabel: () => LocalizedString
			/**
			 * SRM Reference
			 */
			reference: () => LocalizedString
			/**
			 * SRM {value}
			 */
			srmTitle: (arg: { value: number }) => LocalizedString
		}
		gravity: {
			/**
			 * Gravity Conversions
			 */
			title: () => LocalizedString
			/**
			 * Specific Gravity
			 */
			sgLabel: () => LocalizedString
			/**
			 * Degrees Plato
			 */
			platoLabel: () => LocalizedString
			/**
			 * Brix
			 */
			brixLabel: () => LocalizedString
			/**
			 * Reference:
			 */
			reference: () => LocalizedString
			/**
			 * OG 1.000 = 0°P · 1.040 = 10°P · 1.060 = 14.7°P · 1.080 = 19.3°P · 1.100 = 23.8°P
			 */
			referenceBody: () => LocalizedString
		}
		temperature: {
			/**
			 * Temperature
			 */
			title: () => LocalizedString
			/**
			 * Fahrenheit
			 */
			fahrenheitLabel: () => LocalizedString
			/**
			 * Celsius
			 */
			celsiusLabel: () => LocalizedString
			presets: {
				/**
				 * Mash
				 */
				mash: () => LocalizedString
				/**
				 * Sparge
				 */
				sparge: () => LocalizedString
				/**
				 * Pitch Ale
				 */
				pitchAle: () => LocalizedString
				/**
				 * Pitch Lager
				 */
				pitchLager: () => LocalizedString
				/**
				 * Ferment
				 */
				ferment: () => LocalizedString
			}
			/**
			 * {label} ({temp}°F)
			 */
			presetButton: (arg: { label: string, temp: number }) => LocalizedString
		}
		volume: {
			/**
			 * Volume
			 */
			title: () => LocalizedString
			/**
			 * Gallons
			 */
			gallonsLabel: () => LocalizedString
			/**
			 * Litres
			 */
			litresLabel: () => LocalizedString
			/**
			 * Quarts
			 */
			quartsLabel: () => LocalizedString
			/**
			 * Millilitres
			 */
			millilitresLabel: () => LocalizedString
		}
		weight: {
			/**
			 * Weight
			 */
			title: () => LocalizedString
			/**
			 * Pounds
			 */
			poundsLabel: () => LocalizedString
			/**
			 * Ounces
			 */
			ouncesLabel: () => LocalizedString
			/**
			 * Kilograms
			 */
			kilogramsLabel: () => LocalizedString
			/**
			 * Grams
			 */
			gramsLabel: () => LocalizedString
		}
		water: {
			/**
			 * Water Chemistry
			 */
			title: () => LocalizedString
			/**
			 * Volume (gal)
			 */
			volumeLabel: () => LocalizedString
			/**
			 * pH Target
			 */
			phTargetLabel: () => LocalizedString
			/**
			 * SO₄:Cl Ratio ·
			 */
			ratioLabel: () => LocalizedString
			profile: {
				/**
				 * Hoppy / Bitter
				 */
				hoppy: () => LocalizedString
				/**
				 * Balanced Hoppy
				 */
				balancedHoppy: () => LocalizedString
				/**
				 * Balanced
				 */
				balanced: () => LocalizedString
				/**
				 * Malty / Soft
				 */
				malty: () => LocalizedString
			}
		}
	}
	login: {
		/**
		 * Sign in to your brewery
		 */
		tagline: () => LocalizedString
		/**
		 * Username
		 */
		usernameLabel: () => LocalizedString
		/**
		 * you@brewery.com
		 */
		usernamePlaceholder: () => LocalizedString
		/**
		 * Password
		 */
		passwordLabel: () => LocalizedString
		/**
		 * Remember me
		 */
		rememberMe: () => LocalizedString
		/**
		 * Sign in
		 */
		signIn: () => LocalizedString
		/**
		 * sign-in failed
		 */
		signInFailed: () => LocalizedString
		/**
		 * MOSTO · BREWING COMPANION
		 */
		footer: () => LocalizedString
	}
}

export type Formatters = {}
