export const paths = {
  dashboard: '/',
  recipes: '/recipes',
  newRecipe: '/recipes/new',
  recipeDetail: '/recipes/$id',
  brewday: '/brewday',
  inventory: '/inventory',
  newInventoryItem: '/inventory/new',
  inventoryItemDetail: '/inventory/$id',
  equipment: '/equipment',
  newEquipment: '/equipment/new',
  equipmentDetail: '/equipment/$id',
  conversions: '/conversions',
  login: '/login',
} as const
